# Generated by Django 4.2.7 on 2023-11-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_usuario_baja_alter_usuario_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
